name: dsmode

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas=1.5.2
  - numpy=1.24.0
  - matplotlib=3.6.2
  - plotly=5.11.0
  - jupyterlab=3.5.2
  - scikit-learn=1.2.0
  - snakemake=7.19.1